
      <form action="?activity=savepasssword&code=<?=$this->code?>" method="post">
         
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
		
		
        <div class="row"> 
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Definir mon mot de passe et me connecté</button>
          </div>
          <!-- /.col -->
        </div>
      </form> 

 