<SCRIPT type="text/javascript">
 function remplirformation(idf){
	$.ajax({
			type:"POST",
			url:"index.php?activity=getformation", 
			beforeSend :function(){$('#'+idf).html("<option>Encours... </option>");$('#'+idf).trigger("chosen:updated");},
			success:function(response){
				$("#"+idf).html(response); 
				<?php if(!empty($this->idformations)):?> 
					$('#formation1 option[value="<?=$this->idformations?>"]').attr("selected",true);
				<?php endif;?>	
				 
			}
		});
			
}
$(document).ready(function () {
	remplirformation('formation1');
	
	
		inProgress=false;
	 var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { 
  				
 				  
			},
            success: function() { },
            complete: function(response)
            {

			$("#loadzone").remove(); 
                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                     $("#mainbodyinscript").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Succès')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						 // $("#loadzone").remove();  

                     

                }else  if(obj.status=="warning"){
                     $("#messagewarning").html("<div class='alert alert-warning'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Noté Bien')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						//  $("#loadzone").remove();  

                     

                }else{

                    $("#messagetext").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Error')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");
						//$("#loadzone").remove(); 

                }
				 
                return true;

            },
            error: function(response)
            {
				$("#loadzone").remove(); 
                var obj = JSON.parse(response.responseText);
                $("#messagetext").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'>Bravo</h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#myForm").ajaxForm(optmyform); 
		   
	 
});

var ecue=1;
function addCritaire(tableecue){
	ecue++;
	var ligne; 
	ligne="<tr>";  
	ligne+="<td>"; 
	ligne+="<input type='text' name='labelEval[]'>";  
	ligne+="</td>";  
	ligne+="<td>"; 
	ligne+="<input type='text' name='varEval[]'>";  
	ligne+="</td>";  
	ligne+="<td>";
	ligne+="<button type=\"button\" value=\"+\" class='btn btn-danger' onClick=\"$(this).closest('tr').remove();\"><i class=\"fa fa-trash\"><i></button>";
	ligne+="</td>";
	ligne+="</tr>";
	
 
	
	$("#"+tableecue).append(ligne);
	
 
	
}

 
</SCRIPT>
 
 
 
 <div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Configuration des Critères")?></h3> 
    </div>
    <div class="card-body">
	<div id="messagetext"></div>
 <form id="myForm" enctype="multipart/form-data" method="post" action="index.php?activity=savecritaire" class="form-horizontal"> 
 
			<div class="card card-success">
				<div class="card-header">Critères</div>
				<div class="card-body">
				<table class="table table-bordred"> 
					<tbody id="tableecue">
						<tr>
							<td colspan=3> 
								<select  class="form-control form-control-lg"   id="formation1" name="formation" placeholder="Formation" onchange="window.location.href = (window.location.href.split('?')[0])+'?activity=critaire' + '&idf='+this.value" required>
								</select>  
							</td>
							 
						</tr>
						<tr>
							<td colspan=3> 
								<textarea  class="form-control form-control-lg" name="formule"  required><?=!empty($this->scorecalcule) ? $this->scorecalcule : ''?></textarea>  
							</td>
						</tr>
						
						<tr>
							<th>Label</th>
							<th>Critaire</th>
						</tr>
						
						 <?php if($this->critaire):?>
						 
						 <?php foreach($this->critaire as $key => $v):?>
							<tr>  
								 <td>  
									<input type='text' name='labelEval[]' value="<?=$v?>"> 
								 </td>  
								 <td>  
								 <input type='text' name='varEval[]' value="<?=$key?>">  
								 </td>  
								 <td> 
									<button type="button" value="+" class='btn btn-danger' onClick="$(this).closest('tr').remove();"><i class="fa fa-trash"><i></button> 
								 </td> 
							</tr> 
						 <?php endforeach;?>
						 <?php endif;?>
						
					</tbody>
				</table>
				 <button type="button" class="btn btn-warning" onclick="addCritaire('tableecue')" >+ Ajouter</button> 
				</div>
				</div> 
			<input type="submit" value="Ajouter" name="ajouter">
		
		</form>
	</div>
	
</div>
</div>