<SCRIPT type="text/javascript">
 
$(document).ready(function () {
 	
	
	 
	 var optmyformAB = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { 
  				
 				  
			},
            success: function() { },
            complete: function(response)
            {

			$("#loadzone").remove(); 
                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                     $("#messagerefu").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Succès')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						 // $("#loadzone").remove();  

                     

                }else  if(obj.status=="warning"){
                     $("#messagerefu").html("<div class='alert alert-warning'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Noté Bien')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						//  $("#loadzone").remove();  

                     

                }else{

                    $("#messagerefu").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Error')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");
						//$("#loadzone").remove(); 

                }
				 
                return true;

            },
            error: function(response)
            {
				//$("#loadzone").remove(); 
                var obj = JSON.parse(response.responseText);
                $("#messagerefu").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'>Bravo</h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#myFormAB").ajaxForm(optmyformAB); 
		   
	 
});

 

 
</SCRIPT> 
 
	<div id="messagerefu"></div>
 <form id="myFormAB" enctype="multipart/form-data" method="post" action="index.php?activity=saveabstenir&idp=<?=$this->idp?>&idu=<?=$this->idu?>" class="form-horizontal"> 
 
			<div class="card card-success">
			 
				<div class="card-body">
				<table class="table table-bordred"> 
					<tbody id="tableecue">
						<tr>
							<td colspan=3> 
								<select  class="form-control form-control-lg"   id="AbstenirJustifA" name="AbstenirJustifA" placeholder="Motif"required>
								<option value="Cause personnel de tuteur" <?= isset($this->abstenirjustif) &&  isset($this->abstenirjustif['AbstenirJustif']) && $this->abstenirjustif['AbstenirJustif']=='Cause personnel de tuteur' ? "selected='selected'":'' ?>>Cause personnel de tuteur</option>
								<option value="Non reponse" <?= isset($this->abstenirjustif) &&  isset($this->abstenirjustif['AbstenirJustif']) && $this->abstenirjustif['AbstenirJustif']=='Non reponse' ? "selected='selected'":'' ?>>Non reponse</option>
								 
								</select>  
							</td>
							 
						</tr>
						<tr>
							<td colspan=3> 
								<textarea  class="form-control form-control-lg" name="motiftextA"  required><?=isset($this->abstenirjustif['Justif']) && !empty($this->abstenirjustif['Justif']) ? $this->abstenirjustif['Justif'] : ''?></textarea>  
							</td>
						</tr> 
						
					</tbody>
				</table>
 				</div>
				</div> 
			<input type="submit" value="Enregistrer" name="ajouter" class="btn btn-success">
			<input type="submit" value="Annuler" name="annuler" class="btn btn-danger">

		</form>
	 
	 