<div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3>
 		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
       
        <table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></caption>
            <thead>
            <tr>
			<th>N°</th>
			<th></th>
               <th>Formation</th>
			   <th>Niveau</th>
			   <th>Semestre</th> 
			   <th>ECUE</th> 
			   <th>Type</th>
				<th>Nom</th>
				<th>Prénom</th>  
				<th>Grade</th> 	
				<th>Specialite Candidat</th> 	
				
				<th>Etab</th> 
				<th>Univ</th>
				<th>Entreprise</th>
<th>Dossier</th>  				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->liste as $e):?> 
                 
                     
					  <!--niveau--> 
					  <?php foreach ($e["niveau"] as $n):?>  
						 <!--Semestre--> 
						 <?php foreach ($n["semestre"] as $s):?> 
						 <!--ECUE-->
						  <?php foreach ($s["ecue"] as $k=> $ec):?> 
						  <!--Candidat-->
						  <?php foreach ($ec["candidat"] as $p=> $c):?>
							<tr>	
<td><?=++$i?></td>			
<td> 
									<a target="_blank" class="btn btn-success"href="?activity=participation&id=<?=$p?>"><i class="fa fa-eye"></i></a> </td>				
							  <td><?=$e["info"]["label"]?></td>							
							  <td><?=$n["info"]["label"]?></td>
							  <td><?=$s["info"]["label"]?></td>  							
							  <td><?=$ec["info"]["label"]?></td> 
							  <td><?=$c["info"]["typecandidat"]?></td>
							  <td><?=$c["info"]["nom"]?></td>	
							  <td><?=$c["info"]["prenom"]?></td>
							  <td><?=$c["info"]["grade"]?></td>	 
							  <td><?=$c["info"]["specialite"]?></td>	 
							  <td><?=$c["info"]["univ"]?></td>	 
							  <td><?=$c["info"]["etab"]?></td>
							  <td><?=$c["info"]["entreprise"]?></td>	
							  <td> 
									<a class="btn btn-success"href="upload/<?=$c["info"]['pathouvre']?>"><i class="fa fa-download"></i>Dossier</a> </td>							  
							</tr> 
						  <?php $newForm=$newniveau=$newsemestre=true;?>
						  <?php endforeach;?>
						  <?php endforeach;?>
						 <?php endforeach;?>
					 <?php endforeach;?>
              
            <?php endforeach;?>
            </tbody>
        </table>
 
    </div>
</div>
</div>

 