<script>

    $(function(){


        var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { },
            success: function() { },
            complete: function(response)
            {


                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                    $("#messageEdit{Table}_Titre").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Success_save_{Table}')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>");

                       loadPage("lister{Table}","content_lister{Table}");

                    $("#{Table}")[0].reset();

                }else{

                    $("#messageEdit{Table}_Titre").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Error_save_{Table}')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");


                }
                return true;

            },
            error: function(response)
            {
                var obj = JSON.parse(response.responseText);
                $("#messageEdit{Table}_Titre").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Success_save_{Table}')?></h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#{Table}").ajaxForm(optmyform);


    });
</script>

<div id="messageEdit{Table}_Titre"></div>
<h1><?=\Smartedutech\Littlemvc\Langue::getString("Edit_{Table}")?></h1>
<?=$this->form?>
