<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\Smartedutech\Littlemvc\Langue::getString('Chargement_{Table}')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("edit{Table}","edit_edit{Table}");
        loadPage("lister{Table}","content_lister{Table}");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\Smartedutech\Littlemvc\Langue::getString("Edit_{Table}")?></div>
            <div class="box-body" id="edit_edit{Table}">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_{Table}")?></div>
            <div class="box-body" id="content_lister{Table}">

            </div>
        </div>
    </div>
</div>
