 <div class="col-md-8 center">
<div class="card">
<div class="card-header">
	<img src="images/logo-color.svg" alt="Logo UVT" style="width:100%;">
	<hr>
	<h1 class="text-center">Engagement  Tuteur à l’UVT</h1>
</div>

<div class="card-body">
   
	 <p>
	 Le présent engagement a pour objectif de fixer la nature de l’engagement du tuteur/tutrice à l’UVT.  Il /Elle travaille en étroite collaboration avec le /la coordinateur /trice  pédagogique de la formation ainsi qu’avec le service de coordination et de suivi des formations relevant de la direction des affaires pédagogiques.</p>
	 <p>
		En tant qu’acteur clé de la formation à l’UVT, le tuteur est un facilitateur pédagogique ayant une interaction régulière et journalière avec les apprenants. Ces interactions synchrones et asynchrones réactives et proactives, doivent impérativement se faire à travers la plateforme de gestion des apprentissages : <a href="http://fad.uvt.rnu.tn/" target="_blank">http://fad.uvt.rnu.tn/</a>

	 
	 </p>
	 
	 <p>
	 
	<ul> <b>A cet effet, le tuteur est appelé à:</b>     
		<li>	scénariser son espace de cours selon le modèle de l’UVT en coordination  avec le coordinateur pédagogique de la formation, en respectant le plan d’études ;
		</li>
		<li>	faire le point sur la progression des apprentissages par rapport aux objectifs visés afin de réguler le processus de formation ;
		</li>
		<li>	suivre régulièrement et individuellement l’apprenant dans son parcours d’apprentissage, et en cas de problème, remonter  le dysfonctionnement au coordinateur pédagogique ;
		</li>
		<li>	organiser et animer  les séances de regroupement présentiel, ou à distance à raison de 07h par groupe; 
		</li>
		<li>	animer et modérer les forums dédiés au cours en respectant les règles de bonne conduite s'appliquant sur internet (la nétiquette) ;
		</li>
		<li>	contribuer au développement de l’esprit collaboratif et d’appartenance auprès des apprenants ;
		</li>
		<li>	présenter et expliquer les activités d’apprentissage, et leur déroulement, ainsi que leurs critères d’évaluation ;
		</li>
		<li>	élaborer et corriger des épreuves d’évaluation selon les procédures de l’UVT ;
		</li>
		<li>	remettre les notes, dans les délais affichés dans le planning, pour les apprenants et pour les services concernés ;
		</li>
		<li>	utiliser exclusivement les espaces d’encadrement des PFE  sur la plateforme FAD pour l’accompagnement des travaux encadrés.
		</li>

	</ul>

	<ul>
	<b> En plus de ses engagements pédagogiques, le tuteur est appelé à :</b>
	 <li>	veiller au respect de la propriété intellectuelle concernant les ressources pédagogiques du cours ainsi que pour toutes les productions des apprenants ; 
	</li>
	<li>	assister aux réunions organisées par le coordinateur  pédagogique de la formation ;
	</li>
	<li>	participer aux  ateliers  de formations  dédiés aux tuteurs relatifs au programme de formation de formateur de l’UVT. L’obtention des badges réservés aux formations certifiantes de l’UVT est fortement recommandée ;
	</li>
	<li>	assurer la surveillance des séances d’examens ;
	</li>
	<li>	assister aux délibérations des sessions d’examens ;
	</li>
	<li>	utiliser exclusivement la boîte de messagerie électronique de l’UVT dans tous les échanges avec les acteurs de l’UVT.
	</li>
	<li>	à ne pas supprimer aucune ressource ni activité du cours réalisé durant tout le semestre. Une copie de l’espace de cours complet est archivée à l’UVT. Le nettoyage de l’espace de cours est une mission exclusive de l’UVT.
	</li>

	</ul>
	 
	 </p>
	 <p class="text-blue text-center">
	 Il est à noter  qu’un monitoring de l’activité de tutorat est mené par le coordinateur de façon hebdomadaire et semestrielle.
	 </p>
	 </div>
 </div>
  
  </div>