<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>UVT Candidature au tutorat</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="adminlte3/plugins/fontawesome-free/css/all.min.css">
   
  <!-- Theme style -->
  <link rel="stylesheet" href="adminlte3/dist/css/adminlte.min.css">

<!-- icheck bootstrap -->
 
   <link rel="stylesheet" href="adminlte3/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- jQuery -->
<script src="adminlte3/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="adminlte3/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="adminlte3/dist/js/adminlte.min.js"></script>
  
 
 <link rel="stylesheet" type="text/css" href="jsplugins/confimjquery/jquery-confirm.min.css" />

    <script type="text/javascript" src="jsplugins/jqueryform/jquery.form.js"></script>
    <script type="text/javascript" src="jsplugins/confimjquery/jquery-confirm.min.js"></script>

  <script src="adminlte3/plugins/select2/js/select2.full.min.js"></script>
  <script src="adminlte3/bootstrap-switch/js/bootstrap-switch.min.js"></script>
 </head>
<body class="hold-transition">
<div class="content px-2">
  <!-- /.login-logo -->
  <div class="card card-primary align-items-center w-100">
     
    <!-- card-body -->
	<br>
 
    <?php $this->view->generate(true);?>
	 
    <!-- /.card-body --> 
	
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->

<!-- REQUIRED SCRIPTS -->

</body>
</html>
