<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="fr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv='pragma' content='no-cache'>
  <title>Tutorat</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="adminlte3/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="adminlte3/dist/css/adminlte.min.css">
  
  
  <link rel="stylesheet" href="adminlte3/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  
  <!--link rel="stylesheet" href="adminlte3/plugins/datatables/css/jquery.dataTables.min.css"-->
  <!-- jQuery -->
<script src="adminlte3/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="adminlte3/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="adminlte3/dist/js/adminlte.min.js"></script> 

<script src="adminlte3/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="adminlte3/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>

 <link rel="stylesheet" type="text/css" href="jsplugins/confimjquery/jquery-confirm.min.css" />

    <script type="text/javascript" src="jsplugins/jqueryform/jquery.form.js"></script>
    <script type="text/javascript" src="jsplugins/confimjquery/jquery-confirm.min.js"></script>

</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="http://www.uvt.rnu.tn" class="navbar-brand">
         <img src="images/icone2.png" alt="UVT Logo" class="brand-image img-circle elevation-3" style="opacity: .8"-->
        <span class="brand-text font-weight-light"></span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
           <li class="nav-item">
            <a href="?activity=critaire" class="nav-link">Critéres d'évaluation</a>
          </li>
		  <li class="nav-item">
            <a href="?activity=evaluation" class="nav-link">Evaluation</a>
          </li>
		  
		  <li class="nav-item">
            <a href="?activity=mesproposition" class="nav-link">Liste des proposition</a>
          </li>
		  
		  <li class="nav-item">
            <a href="?activity=tristuteur" class="nav-link">Classement des dossiers</a>
          </li> 
        </ul> 
        <!-- SEARCH FORM -->
        
      </div>
	 <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto"> 
		<li class="nav-item">
			<a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
				<i class="fas fa-th-large"></i>
			</a>
		</li>
	</ul>
    </div>
  </nav>
  <!-- /.navbar -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"> Tutorat <small><?=date("Y")?></small></h1>
          </div><!-- /.col -->
          <!--div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#"></a></li>
              <li class="breadcrumb-item"><a href="#"></a></li>
              <li class="breadcrumb-item active"></li>
            </ol>
          </div--><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container">
      <?php $this->view->generate(true);?>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      http://www.uvt.rnu.tn
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->


</body>
</html>
