<script>

    function loadPage(page,zone){
        $.ajax({
            type:"POST"
            ,url:"index.php?activity="+page

            ,beforeSend:function(){
                $('#'+zone).html("<i class='icon fa fa-gears'></i> <?=\Smartedutech\Littlemvc\Langue::getString('Chargement_roles')?>");
            }
            ,success:function(reponse){
                $('#'+zone).html(reponse);
            }
        });
    }

    $(function(){
        loadPage("editroles","edit_editroles");
        loadPage("listerroles","content_listerroles");
    });
</script>

<div class ="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\Smartedutech\Littlemvc\Langue::getString("Edit_roles")?></div>
            <div class="box-body" id="edit_editroles">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_roles")?></div>
            <div class="box-body" id="content_listerroles">

            </div>
        </div>
    </div>
</div>
