<?php

global $_Routes;
$_Routes=array(
    "editformations"=>array(
        "Module"=>"admin"
        ,"Controller"=>"formations"
        ,"Action"=>"editformations"
        ,"Roles"=>array()
),
"edittypeformation"=>array(
    "Module"=>"admin"
    ,"Controller"=>"typeformation"
    ,"Action"=>"edittypeformation"
    ,"Roles"=>array()
),
"listertypeformation"=>array(
    "Module"=>"admin"
    ,"Controller"=>"typeformation"
    ,"Action"=>"listertypeformation"
    ,"Roles"=>array()
),
"consultertypeformation"=>array(
    "Module"=>"admin"
    ,"Controller"=>"typeformation"
    ,"Action"=>"consultertypeformation"
    ,"Roles"=>array()
),
"gestiontypeformation"=>array(
    "Module"=>"admin"
    ,"Controller"=>"typeformation"
    ,"Action"=>"gestiontypeformation"
    ,"Roles"=>array()
),
"deletetypeformation"=>array(
    "Module"=>"admin"
    ,"Controller"=>"typeformation"
    ,"Action"=>"deletetypeformation"
    ,"Roles"=>array()
),
"savetypeformation"=>array(
    "Module"=>"admin"
    ,"Controller"=>"typeformation"
    ,"Action"=>"savetypeformation"
    ,"Roles"=>array()
),
"listerformations"=>array(
        "Module"=>"admin"
        ,"Controller"=>"formations"
        ,"Action"=>"listerformations"
        ,"Roles"=>array()
),
"consulterformations"=>array(
        "Module"=>"admin"
        ,"Controller"=>"formations"
        ,"Action"=>"consulterformations"
        ,"Roles"=>array()
),
"gestionformations"=>array(
        "Module"=>"admin"
        ,"Controller"=>"formations"
        ,"Action"=>"gestionformations"
        ,"Roles"=>array("Admin"=>"Admin")
),
"deleteformations"=>array(
        "Module"=>"admin"
        ,"Controller"=>"formations"
        ,"Action"=>"deleteformations"
        ,"Roles"=>array()
),
"saveformations"=>array(
        "Module"=>"admin"
        ,"Controller"=>"formations"
        ,"Action"=>"saveformations"
        ,"Roles"=>array()
),
  "index"=>array(
                      "Module"=>"defaultmodule"
                      ,"Controller"=>"index"
                      ,"Action"=>"index"
                      ,"Roles"=>array()
  ), 
  "editroles"=>array(
    "Module"=>"admin"
    ,"Controller"=>"roles"
    ,"Action"=>"editroles"
    ,"Roles"=>array()
),
"listerroles"=>array(
    "Module"=>"admin"
    ,"Controller"=>"roles"
    ,"Action"=>"listerroles"
    ,"Roles"=>array()
),
"consulterroles"=>array(
    "Module"=>"admin"
    ,"Controller"=>"roles"
    ,"Action"=>"consulterroles"
    ,"Roles"=>array()
),
"gestionroles"=>array(
    "Module"=>"admin"
    ,"Controller"=>"roles"
    ,"Action"=>"gestionroles"
    ,"Roles"=>array()
),
"deleteroles"=>array(
    "Module"=>"admin"
    ,"Controller"=>"roles"
    ,"Action"=>"deleteroles"
    ,"Roles"=>array()
),
"saveroles"=>array(
    "Module"=>"admin"
    ,"Controller"=>"roles"
    ,"Action"=>"saveroles"
    ,"Roles"=>array()
),
  "menuadmin"=>array(
                      "Module"=>"defaultmodule"
                      ,"Controller"=>"index"
                      ,"Action"=>"menuadmin"
                      ,"Roles"=>array()
  ),
  
  "login"=>array(
      "Module"=>"defaultmodule"
      ,"Controller"=>"authentification"
      ,"Action"=>"login"
      ,"Roles"=>array()
  ),
    
  
  "authentifier"=>array(
      "Module"=>"defaultmodule"
      ,"Controller"=>"authentification"
      ,"Action"=>"authentifier"
      ,"Roles"=>array( )
  )
,"deconnecter"=>array(
      "Module"=>"defaultmodule"
    ,"Controller"=>"authentification"
    ,"Action"=>"deconnecter"
    ,"Roles"=>array( )
  )

,"acceuil"=>array(
      "Module"=>"default"
  ,"Controller"=>"authentification"
  ,"Action"=>"acceuil"
  ,"Roles"=>array( )
  ) ,
  
  "editpersonnes"=>array(
    "Module"=>"admin"
    ,"Controller"=>"personnes"
    ,"Action"=>"editpersonnes"
    ,"Roles"=>array()
),
"listerpersonnes"=>array(
    "Module"=>"admin"
    ,"Controller"=>"personnes"
    ,"Action"=>"listerpersonnes"
    ,"Roles"=>array()
),
"consulterpersonnes"=>array(
    "Module"=>"admin"
    ,"Controller"=>"personnes"
    ,"Action"=>"consulterpersonnes"
    ,"Roles"=>array()
),
"gestionpersonnes"=>array(
    "Module"=>"admin"
    ,"Controller"=>"personnes"
    ,"Action"=>"gestionpersonnes"
    ,"Roles"=>array()
),
"deletepersonnes"=>array(
    "Module"=>"admin"
    ,"Controller"=>"personnes"
    ,"Action"=>"deletepersonnes"
    ,"Roles"=>array()
),
"savepersonnes"=>array(
    "Module"=>"admin"
    ,"Controller"=>"personnes"
    ,"Action"=>"savepersonnes"
    ,"Roles"=>array()
)

 
  
     
);
