 
 <SCRIPT type="text/javascript">
 function remplirformation(idf){
	$.ajax({
			type:"POST",
			url:"index.php?activity=getformation", 
			beforeSend :function(){$('#'+idf).html("<option>Encours... </option>");$('#'+idf).trigger("chosen:updated");},
			success:function(response){
				$("#"+idf).html(response); 
				 
			}
		}); 
}
$(document).ready(function () {
	remplirformation('formation1');
	
	
		inProgress=false;
	 var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { 
				$("#encours").html(percentComplete);
				$("#progresschifre").html(percentComplete);
				
				$("#progressbar").css({'width': percentComplete+'%'}); 
				 if(!inProgress){
				 $("#formload").append("<div id=\"loadzone\" class=\"overlay\" > <i class=\"fas fa-2x fa-sync-alt fa-spin\"i></i><b id=\"progresschifre\"></b></div>");
					inProgress=true;
				} 
			},
            success: function() { },
            complete: function(response)
            {

$("#loadzone").remove(); 
                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                     $("#mainbodyinscript").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Succès')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						 // $("#loadzone").remove();  

                     

                }else  if(obj.status=="warning"){
                     $("#messagewarning").html("<div class='alert alert-warning'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Noté Bien')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						//  $("#loadzone").remove();  

                     

                }else{

                    $("#progresschifre").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Error')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");
						//$("#loadzone").remove(); 

                }
				 
                return true;

            },
            error: function(response)
            {
				$("#loadzone").remove(); 
                var obj = JSON.parse(response.responseText);
                $("#progresschifre").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'>Bravo</h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#myForm").ajaxForm(optmyform); 
	 
});

var ecue=1;
function addecue(tableecue){
	ecue++;
	var ligne; 
	ligne="<tr>";  
	ligne+="<td>"; 
	ligne+="<select  class=\"form-control form-control-lg\" onchange=\"changeformation(this.value,'unite"+ecue+"')\" id=\"formation"+ecue+"\" name=\"formation[]\" placeholder=\"Formation\"> </select>";  
	ligne+="</td>";  
	ligne+="<td>";
	ligne+="<button type=\"button\" value=\"+\" class='btn btn-danger' onClick=\"$(this).closest('tr').remove();\"><i class=\"fa fa-trash\"><i></button>";
	ligne+="</td>";
	ligne+="</tr>";
	
 
	
	$("#"+tableecue).append(ligne);
	
	remplirformation("formation"+ecue);
	
}
</SCRIPT>
 
 
 
 <div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Add_user_coordinateur")?></h3> 
    </div>
    <div class="card-body">
 <form id="myForm" enctype="multipart/form-data" method="post" action="index.php?activity=saveuser"   class="form-horizontal">
			 
			<div class="form-group row">
				<label for="nom" class="col-sm-3 col-form-label">Nom <b class="text-red">*</b></label>
				<div class="col-sm-9">
				<input type="text" class="form-control form-control-lg" id="nom"  name="nom" placeholder="Nom" required>
				</div>
			</div>

			<div class="form-group row">
				<label for="nom" class="col-sm-3 col-form-label">Prénom <b class="text-red">*</b></label>
				<div class="col-sm-9">
				<input type="text" class="form-control form-control-lg" id="prenom" name="prenom" placeholder="Prénom" required>
				</div>
			</div>
			 
			<div class="form-group row">
				<label for="email" class="col-sm-3 col-form-label">Email <b class="text-red">*</b></label>
				<div class="col-sm-9">
				<input type="email" class="form-control form-control-lg" id="email" name="email"placeholder="email" required>
				</div>
			</div>

			<div class="form-group row">
				<label for="tel" class="col-sm-3 col-form-label">Numéro de téléphone portable <b class="text-red">*</b></label>
				<div class="col-sm-9">
				<input type="text" class="form-control form-control-lg" id="tel" name="tel" placeholder="tel" required>
				</div>
			</div>
			<div class="card card-success">
				<div class="card-header">Formation</div>
				<div class="card-body">
				<table class="table table-bordred">

				<tbody id="tableecue">
				<tr>
					<td> 
						<select  class="form-control form-control-lg"   id="formation1" name="formation[]" placeholder="Formation" required>
						</select>  
					</td>
					 
				</tr>
				</tbody>
				</table>
				 <button type="button" class="btn btn-warning" onclick="addecue('tableecue')" >+ Ajouter</button>

				</div>
				</div>

			 
			<input type="submit" value="Ajouter" name="ajouter">
		
		</form>
	</div>
	
</div>
</div>