<script type="text/javascript">
 
 var tableToExcel = (function() {
        var uri = 'data:application/vnd.ms-excel;charset=UTF-8;base64,'
            , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
            , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
            , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
        return function(table, name) {
            if (!table.nodeType) table = document.getElementById(table)
            var ctx = {worksheet: name || 'Worksheet', table:   table.innerHTML }
            window.location.href = uri + base64(format(template, ctx))
        }
    })();

</script>
<div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_utilisateur")?></h3>
        <a href="?activity=exportxls" class="btn btn-flat btn-success"><i class="fas fa-file"></i> Export XLS</a>
		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
       
        <table class="table table-striped table-bordered" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Lister_utilisateur")?></caption>
            <thead>
            <tr>
                <?php foreach ($this->Header as $keyhead => $head):?>
                    <th><?=\Smartedutech\Littlemvc\Langue::getString($head)?></th>
                <?php endforeach;?>
				<th>Invitation</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->liste as $e):?>
                <tr>
                    <?php foreach ($this->Header as $keyhead => $head):?>
                    <?php if(count($this->LinkedId) && isset($this->LinkedId['$keyhead'])):?>
                    <td></td>
                    <?php elseif($keyhead!='acces') :?>
                        <td><?=$e["$keyhead"]?></td>
					 <?php else  :?>
					 <td>
					 <?php 
					 $listeformation=!empty($e["$keyhead"]) ? json_decode($e["$keyhead"],true):[];
					 foreach($listeformation as $f){
						 $formationRec= Smartedutech\Littlemvc\dbadapter::SelectSQL("SELECT * from formations where idformations = ".$f['formation']);
						 echo $formationRec[0]['Label']."; ";
					 }
					 
					 
					 ?>
					 </td>
                    <?php endif;?>
                    <?php endforeach;?>
                     
					 <td> 
					 <a class="btn btn-success"href="?activity=invitation&id=<?=$e['idpersonnes']?>"><i class="fa fa-email"></i>Invitation</a>
                     

                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
 
    </div>
</div>
</div>