 
<div class="row">
<div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3>
 		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
	<div class="row">
	<div class="col-3"> 
	    <table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Nombre de participation globale")?></caption>
            <thead>
            <tr>
			 
            <th>Candidats</th>     				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->byParticipeECUE as $e):?> 
 				<tr>	
				     							
				  <td><?=$e["nbrpartice"]?></td>
				</tr>   
            <?php endforeach;?>
            </tbody>
        </table>
 
	</div>
    <div class="col-9">   
        <table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Nombre de candidat par type (enseignant/pro.")?></caption>
            <thead>
            <tr>
			<th>N°</th>
			<th>Type candidat</th>
            <th>Candidats</th>     				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->byType as $e):?> 
 				<tr>	
				  <td><?=++$i?></td> 
				  <td><?=$e["typecandidat"]?></td>							
				  <td><?=$e["nbrpartice"]?></td>
				</tr>   
            <?php endforeach;?>
            </tbody>
        </table>
		</div>
    </div>
	</div>
</div>
</div>
</div>



<div class="row">
<div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3>
 		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
       
        <table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Nombre de candidat par formation")?></caption>
            <thead>
            <tr>
			<th>N°</th>
			<th>Formation</th>
            <th>Candidats</th>     				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->byFormation as $e):?> 
 				<tr>	
				  <td><?=++$i?></td> 
				  <td><?=$e["label"]?></td>							
				  <td><?=$e["nbrpartice"]?></td>
				</tr>   
            <?php endforeach;?>
            </tbody>
        </table>
 
    </div>
</div>
</div>
</div>

<div class="row">
<div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3>
 		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
	<div class="row">
       <div class="col-6">
        <table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></caption>
            <thead>
            <tr>
			<th>N°</th>
			<th>Université</th>
            <th>Candidats</th>     				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->byUniv as $e):?> 
 				<tr>	
				  <td><?=++$i?></td> 
				  <td><?=$e["label"]?></td>							
				  <td><?=$e["nbrpartice"]?></td>
				</tr>  
 
            <?php endforeach;?>
            </tbody>
        </table>
		</div>
 
	<div class="col-6">
 
		<table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Nombre de candidat par etablissement")?></caption>
            <thead>
            <tr>
			<th>N°</th>
			<th>Etablissement</th>
            <th>Candidats</th>     				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->byEtab as $e):?> 
 				<tr>	
				  <td><?=++$i?></td> 
				  <td><?=$e["label"]?></td>							
				  <td><?=$e["nbrpartice"]?></td>
				</tr>  
 
            <?php endforeach;?>
            </tbody>
        </table>
 
 
	</div>
	</div>
    </div>
</div>
</div>
</div>
 
 
  