<SCRIPT type="text/javascript">


function remplirformation(idf){
	$.ajax({
			type:"POST",
			url:"index.php?activity=getformation", 
			beforeSend :function(){$('#'+idf).html("<option>Encours... </option>");$('#'+idf).trigger("chosen:updated");},
			success:function(response){
				$("#"+idf).html(response); 
				 
			}
		}); 
}
function changeformation(idf,idu){
	 
            
			/****************Chargement de la liste des formations**********************/
				$.ajax({
					type:"POST",
					url:"index.php?activity=getunite",
					data:{idformation:idf,semestre: $('#semestre').val()},
					beforeSend :function(){
						$('#'+idu).html("<option>Encours... </option>");
					$('#'+idu).trigger("chosen:updated");
					},
					success:function(response){
						$("#"+idu).html(response); 
						 
					}
				});
}


function changeSemestre(idf,idu){
	 
            
			/****************Chargement de la liste des formations**********************/
				$.ajax({
					type:"POST",
					url:"index.php?activity=getunite",
					data:{idformation:$("#formation1").val(),semestre: idf },
					beforeSend :function(){
						$('#'+idu).html("<option>Encours... </option>");
					$('#'+idu).trigger("chosen:updated");
					},
					success:function(response){
						$("#"+idu).html(response); 
						 
					}
				});
}

$(document).ready(function () {
	
	$.ajax({
			type:"POST",
			url:"index.php?activity=getuniversity",
			 
			beforeSend :function(){
				$('#univ').html("<option>Encours... </option>"); 
			},
			success:function(response){
				$("#univ").html(response); 
				  
			}
		});
	
	$.ajax({
			type:"POST",
			url:"index.php?activity=getsemestre",
			 
			beforeSend :function(){
				$('#semestre').html("<option>Encours... </option>"); 
			},
			success:function(response){
				$("#semestre").html(response); 
				  
			}
		});
	
	$("#univ").change(function(){
            var opt=$(this).val();
            
			/****************Chargement de la liste des formations**********************/
				$.ajax({
					type:"POST",
					url:"index.php?activity=getetablissement",
					data:{univ:opt },
					beforeSend :function(){$('#etab').html("<option>Encours... </option>");$('#etab').trigger("chosen:updated");},
					success:function(response){
						$("#etab").html(response); 
						 
					}
				});
	});
	
	
	  
            
	/****************Chargement de la liste des formations**********************/
	
	remplirformation("formation1");
	
	
	$("#formation").change(function(){
           
	});
		
		
		
		$.ajax({
			type:"POST",
			url:"index.php?activity=getgrade", 
			beforeSend :function(){$('#grade').html("<option>Encours... </option>");$('#grade').trigger("chosen:updated");},
			success:function(response){
				$("#grade").html(response); 
				 
			}
		}); 
	
	
	$('input[name="univprive"]').click(function(){
            var opt=$(this).val(); 
            
			/****************Chargement de la liste des formations**********************/
			if(opt=="enseignant"){
				 $(".universitaire").show();
				 $(".profesionnel").hide();
				 
				 //$('#entreprise').removeAttr('required');
				//$('#postefonction').removeAttr('required');

				// $('#univ').attr('required', 'required');
				//$('#etab').attr('required', 'required');
				
				  
				 $.ajax({
					type:"POST",
					url:"index.php?activity=getgrade", 
					data:{typegrade:'univ' },
					beforeSend :function(){$('#grade').html("<option>Encours... </option>");$('#grade').trigger("chosen:updated");},
					success:function(response){
						$("#grade").html(response); 
						 
					}
				}); 
			}else{
				$(".universitaire").hide();
				$(".profesionnel").show();
				
				//$('#entreprise').attr('required', 'required');
				//$('#postefonction').attr('required', 'required');
				
				//$('#univ').removeAttr('required');
				//$('#etab').removeAttr('required');
				
				$.ajax({
					type:"POST",
					url:"index.php?activity=getgrade",
					data:{typegrade:'pro' },					
					beforeSend :function(){$('#grade').html("<option>Encours... </option>");$('#grade').trigger("chosen:updated");},
					success:function(response){
						$("#grade").html(response); 
						 
					}
				}); 
			}
				
	});
	
	
	
	
	
	
	
	
	
	
	
    $('#tabliste').DataTable({
       
		paging: false,
		order: [[2, 'desc']],
		//responsive: true,
	 
    });
});
 
    function consulter(params){

          $.ajax({
              type:"POST"
              ,url: "index.php?activity=consulterparticipation"
              ,data:{idmatiere:params}
              ,beforeSend:function(){
                  $('#edit_editmatiere').html("<i class='icon fa fa-gears'></i> chargement Encours...");
              }
              ,success:function(reponse){
                   $('#edit_editmatiere').html(reponse);
              }
          });

    }
 

 var tableToExcel = (function() {
        var uri = 'data:application/vnd.ms-excel;charset=UTF-8;base64,'
            , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
            , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
            , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
        return function(table, name) {
            if (!table.nodeType) table = document.getElementById(table)
            var ctx = {worksheet: name || 'Worksheet', table:   table.innerHTML }
            window.location.href = uri + base64(format(template, ctx))
        }
    })();

</script>



<div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3> 
    </div>
    <div class="card-body">
		<form action="" method="POST">
			<div class="form-group row clearfix">
	  <div class="icheck-primary d-inline">
		<input type="radio" id="univprive1" name="univprive"  value="enseignant">
		<label for="univprive1">Enseignant </label>
	  </div>
	  <div class="col-1"></div>
	  <div class="icheck-danger d-inline">
		<input type="radio" id="univprive2" name="univprive" value="professionnel">
		<label for="univprive2">Professionnel </label>
	  </div>
	  
	</div>
	
	<hr>	
	<div class="form-group row clearfix profesionnel" style="display: none;">
		  <div class="icheck-warning d-inline">
			<input type="radio" id="secteur1" name="secteurjob"  value="Secteur public">
			<label for="secteur1">Secteur public </label>
		  </div>
		  <div class="col-1"></div>
		  <div class="icheck-success  d-inline">
			<input type="radio" id="secteur2" name="secteurjob" value="Secteur privé">
			<label for="secteur2">Secteur privé </label>
		  </div>
		  
		</div>
		<div class="form-group row universitaire">
	<label for="univ" class="col-sm-3 col-form-label">Université/DGET <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="univ" name="univ"  placeholder="univ"  >
	</select>
	</div>
</div>

<div class="form-group row universitaire">
	<label for="etab" class="col-sm-3 col-form-label">Etablissement <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="etab" name="etab" placeholder="etab"  >
	</select>
	</div>
</div>

<div class="form-group row ">
	<label for="etab" class="col-sm-3 col-form-label">Grade <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="grade" name="grade" placeholder="grade"  >
	</select>
	</div>
</div>

		<div class="form-group row ">
			<label for="etab" class="col-sm-3 col-form-label">Formation <b class="text-red">*</b></label>
			<div class="col-sm-9"> 

				<select  class="form-control form-control-lg" onchange="changeformation(this.value,'unite1')" id="formation1" name="formation" placeholder="Formation"  >
				</select>  
			</div>
		</div> 

		<div class="form-group row ">
			<label for="etab" class="col-sm-3 col-form-label">Semestre <b class="text-red">*</b></label>
			<div class="col-sm-9"> 

				<select  class="form-control form-control-lg" onchange="changeSemestre(this.value,'unite1')" id="semestre" name="semestre" placeholder="Semestre"  >
				</select>  
			</div>
		</div>
		
		<div class="form-group row ">
			<label for="etab" class="col-sm-3 col-form-label">ECUE <b class="text-red">*</b></label>
			<div class="col-sm-9"> 

					<select  class="form-control form-control-lg" id="unite1" name="unite" placeholder="Unité"  >
				</select> 
			</div>
		</div>
		<input type="submit" value="rechercher" name="rechercher">
		
		</form>
	</div>
	
</div>
</div>

 <div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3>
 		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
       
        <table style="width:100%;" class="table table-bordered table-striped dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></caption>
            <thead>
            <tr>
			<th>N°</th>
			<th>N°Dossier</th>
			<th><i class="fa fa-eye"></i></th>
               <th>Formation</th>
			   <th>Niveau</th>
			   <th>Semestre</th> 
			   <th>ECUE</th> 
			   <th>Type</th>
				<th>Nom</th>
				<th>Prénom</th>  
				<th>Grade</th> 	
				<th>Specialite Candidat</th> 
				<th>Etab</th> 
				<th>Univ</th>
				<th>Entreprise</th>
				<th>Dossier</th>  				
            </tr>
            </thead>
            <tbody>
            <?php $i=0; foreach ($this->liste as $e):?> 
                 
                     
					  <!--niveau--> 
					  <?php foreach ($e["niveau"] as $n):?>  
						 <!--Semestre--> 
						 <?php foreach ($n["semestre"] as $s):?> 
						 <!--ECUE-->
						  <?php foreach ($s["ecue"] as $k=> $ec):?> 
						  <!--Candidat-->
						  <?php foreach ($ec["candidat"] as $p => $c):?>
						   
							<tr>	
<td><?=++$i?></td>
<td><?=$c["info"]["id"]?></td>
<td><a target="_blank" class="btn btn-success"href="?activity=participation&id=<?=$p?>"><i class="fa fa-eye"></i></a> </td>								
							  <td><?=$e["info"]["label"]?></td>							
							  <td><?=$n["info"]["label"]?></td>
							  <td><?=$s["info"]["label"]?></td>  							
							  <td><?=$ec["info"]["label"]?></td> 
							  <td><?=$c["info"]["typecandidat"]?></td>
							  <td><?=$c["info"]["nom"]?></td>	
							  <td><?=$c["info"]["prenom"]?></td>
							  <td><?=$c["info"]["grade"]?></td>	 
							  <td><?=$c["info"]["specialite"]?></td>	 
							  <td><?=$c["info"]["univ"]?></td>	 
							  <td><?=$c["info"]["etab"]?></td>
							  <td><?=$c["info"]["entreprise"]?></td>	
							  <td> 
									<a class="btn btn-success"href="upload/<?=$c["info"]['pathouvre']?>"><i class="fa fa-download"></i>Dossier</a> </td>							  
							</tr> 
						  <?php $newForm=$newniveau=$newsemestre=true;?>
						  <?php endforeach;?>
						  <?php endforeach;?>
						 <?php endforeach;?>
					 <?php endforeach;?>
              
            <?php endforeach;?>
            </tbody>
        </table>
 
    </div>
</div>
</div>

 