  <script type="text/javascript">
$(document).ready(function () {
    $('#tabliste').DataTable({
       
		paging: false,
		order: [[2, 'desc']],
		//responsive: true,
	 
    });
});
 
    function consulter(params){

          $.ajax({
              type:"POST"
              ,url: "index.php?activity=consulterparticipation"
              ,data:{idmatiere:params}
              ,beforeSend:function(){
                  $('#edit_editmatiere').html("<i class='icon fa fa-gears'></i> chargement Encours...");
              }
              ,success:function(reponse){
                   $('#edit_editmatiere').html(reponse);
              }
          });

    }
 

 var tableToExcel = (function() {
        var uri = 'data:application/vnd.ms-excel;charset=UTF-8;base64,'
            , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
            , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
            , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
        return function(table, name) {
            if (!table.nodeType) table = document.getElementById(table)
            var ctx = {worksheet: name || 'Worksheet', table:   table.innerHTML }
            window.location.href = uri + base64(format(template, ctx))
        }
    })();

</script>

 <div class="col-12">
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title"><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></h3>
 		<input type="button" onclick="tableToExcel('tabliste', 'listeCandiat')" value="Export to Excel"/>

    </div>
    <div class="card-body">
       
        <table style="width:100%;" class="table table-bordered dataTable col-12" id="tabliste"style="width:100%;">
            <caption><?=\Smartedutech\Littlemvc\Langue::getString("Lister_particiapant")?></caption>
            <thead>
            <tr>
			
               <th>Formation</th>
			   <th>Niveau</th>
			   <th>Semestre</th> 
			   <th>ECUE</th> 
			   <th>N°</th>
			   <th>Type</th> 
				<th>Nom</th>
				<th>Prénom</th>  
				<th>Grade</th> 	
				<th>Specialite Candidat</th>  
				<th>Etab</th> 
				<th>Univ</th>
				<th>Entreprise</th>
				<th>Dossier</th>  				
            </tr>
            </thead>
            <tbody>
            <?php  foreach ($this->liste as $e):?> 
                 <tr> 
					  <td rowspan="<?=$e["count"]?>"><?=$e["info"]["label"]?></td> 
					  <!--niveau--> 
					  <?php $newniveau=false;?>
					  <?php foreach ($e["niveau"] as $n):?>  
					  <?php if($newniveau):?>
							   <tr>							  
							<?php endif;?>
					  <td rowspan="<?=$n["count"]?>"><?=$n["info"]["label"]?></td>
					    
					   <?php $newniveau=true;?>
						 <!--Semestre--> 
						 <?php $newsemestre=false;?>
						 <?php foreach ($n["semestre"] as $s):?>
							<?php if($newsemestre):?>
							   <tr>							  
							<?php endif;?>						 
						 <td rowspan="<?=$s["count"]?>"><?=$s["info"]["label"]?></td>
						  
						<?php $newsemestre=true;?>						 
						 <!--ECUE-->
						 <?php $newecue=false;?>
						  <?php foreach ($s["ecue"] as $k=> $ec):?>
							<?php $i=0;if($newecue):?>
							   <tr>							  
							<?php endif;?>
						   <td rowspan="<?=$ec["count"]?>"><?=$ec["info"]["label"]?> (<?=$s["info"]["label"]?>)</td>
						   
							<?php $newecue=true;?>						   
						  <!--Candidat-->
						  <?php $candidat=false;?>
						  <?php foreach ($ec["candidat"] as $c):?>
							  <?php if($candidat):?>
								<tr>							  
							  <?php endif;?>
							  <td><?=++$i?></td>		 
							  <td><?=$c["info"]["typecandidat"]?></td>
							  <td><?=$c["info"]["nom"]?></td>	
							  <td><?=$c["info"]["prenom"]?></td>
							  <td><?=$c["info"]["grade"]?></td>	 
							  <td><?=$c["info"]["specialite"]?></td>	 
							  <td><?=$c["info"]["univ"]?></td>	 
							  <td><?=$c["info"]["etab"]?></td>
							  <td><?=$c["info"]["entreprise"]?></td>	
							  <td> 
									<a class="btn btn-success"href="upload/<?=$c["info"]['pathouvre']?>"><i class="fa fa-download"></i>Dossier</a> </td>							  
							  </tr> 
						  <?php $candidat=true;?>
						  <?php endforeach;?>
						  <?php endforeach;?>
						 <?php endforeach;?>
					 <?php endforeach;?>
              
            <?php endforeach;?>
            </tbody>
        </table>
 
    </div>
</div>
</div>

 