<script src='https://www.google.com/recaptcha/api.js'></script>

<SCRIPT type="text/javascript">

$(function() {
	inProgress=false;
	 var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { 
				$("#encours").html(percentComplete);
				$("#progresschifre").html(percentComplete);
				
				$("#progressbar").css({'width': percentComplete+'%'}); 
				 if(!inProgress){
				 $("#formload").append("<div id=\"loadzone\" class=\"overlay\" > <i class=\"fas fa-2x fa-sync-alt fa-spin\"i></i><b id=\"progresschifre\"></b></div>");
					inProgress=true;
				} 
			},
            success: function() { },
            complete: function(response)
            {


                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                     $("#mainbodyinscript").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Succés')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						  $("#loadzone").remove();  

                     

                }else  if(obj.status=="warning"){
                     $("#messagewarning").html("<div class='alert alert-warning'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Noté Bien')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>"); 
 
						  $("#loadzone").remove();  

                     

                }else{

                    $("#progresschifre").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Error')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");
						$("#loadzone").remove(); 

                }
                return true;

            },
            error: function(response)
            {
                var obj = JSON.parse(response.responseText);
                $("#progresschifre").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'>Bravo</h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");
$("#loadzone").remove(); 
                return false;
            }

        };

          $("#myForm").ajaxForm(optmyform); 
	
	$.ajax({
			type:"POST",
			url:"index.php?activity=getuniversity",
			 
			beforeSend :function(){
				$('#univ').html("<option>Encours... </option>"); 
			},
			success:function(response){
				$("#univ").html(response); 
				  
			}
		});
	
	$("#univ").change(function(){
            var opt=$(this).val();
            
			/****************Chargement de la liste des formations**********************/
				$.ajax({
					type:"POST",
					url:"index.php?activity=getetablissement",
					data:{univ:opt },
					beforeSend :function(){$('#etab').html("<option>Encours... </option>");$('#etab').trigger("chosen:updated");},
					success:function(response){
						$("#etab").html(response); 
						 
					}
				});
	});
	
	
	  
            
	/****************Chargement de la liste des formations**********************/
	$("#formation").change(function(){
            var opt=$(this).val();
            
			/****************Chargement de la liste des formations**********************/
				$.ajax({
					type:"POST",
					url:"index.php?activity=getunite",
					data:{idformation:opt },
					beforeSend :function(){
						$('#unite').html("<option>Encours... </option>");
					$('#unite').trigger("chosen:updated");
					},
					success:function(response){
						$("#unite").html(response); 
						 
					}
				});
	});
		$.ajax({
			type:"POST",
			url:"index.php?activity=getformation", 
			beforeSend :function(){$('#formation').html("<option>Encours... </option>");$('#formation').trigger("chosen:updated");},
			success:function(response){
				$("#formation").html(response); 
				 
			}
		}); 
		
		
		$.ajax({
			type:"POST",
			url:"index.php?activity=getgrade", 
			beforeSend :function(){$('#grade').html("<option>Encours... </option>");$('#grade').trigger("chosen:updated");},
			success:function(response){
				$("#grade").html(response); 
				 
			}
		}); 
		
		$("#description").keyup(function (event) {
			 
			var max = 1000;
			var mots = $.trim($(this).val()).split(" ");
			var len = $(this).val().length;
			var char = max - len;
			$("#nbrcar").html(len);
			var nbrmot=(len==0 ? 0 : mots.length);
		    $("#nbrmots").html(nbrmot);
			 if(nbrmot>300){
				 $("#nbrmots").css({ 'color': 'red', 'font-size': '16px' });
			 }else{
				 $("#nbrmots").css({ 'color': 'green', 'font-size': '16px' });
			 }
			 
			 if(len>1000){
				 $("#nbrcar").css({ 'color': 'red', 'font-size': '16px' });
			 }else{
				 $("#nbrcar").css({ 'color': 'green', 'font-size': '16px' });
			 }

		  });
		  
		  
		  
	 $('input[name="univprive"]').click(function(){
            var opt=$(this).val(); 
            
			/****************Chargement de la liste des formations**********************/
			if(opt=="enseignant"){
				 $(".universitaire").show();
				 $(".profesionnel").hide();
				 
				 $('#entreprise').removeAttr('required');
				$('#postefonction').removeAttr('required');

				 $('#univ').attr('required', 'required');
				$('#etab').attr('required', 'required');
				
				  
				 $.ajax({
					type:"POST",
					url:"index.php?activity=getgrade", 
					data:{typegrade:'univ' },
					beforeSend :function(){$('#grade').html("<option>Encours... </option>");$('#grade').trigger("chosen:updated");},
					success:function(response){
						$("#grade").html(response); 
						 
					}
				}); 
			}else{
				$(".universitaire").hide();
				$(".profesionnel").show();
				
				$('#entreprise').attr('required', 'required');
				$('#postefonction').attr('required', 'required');
				
				$('#univ').removeAttr('required');
				$('#etab').removeAttr('required');
				
				$.ajax({
					type:"POST",
					url:"index.php?activity=getgrade",
					data:{typegrade:'pro' },					
					beforeSend :function(){$('#grade').html("<option>Encours... </option>");$('#grade').trigger("chosen:updated");},
					success:function(response){
						$("#grade").html(response); 
						 
					}
				}); 
			}
				
	});
	
	 
});
</SCRIPT>

<style>

@media only screen and (min-width: 768px) {
	.textpmarg{
		line-height : normal;
	}
}

@media only screen and (min-width: 992px) {
	.textpmarg{
		line-height : 0;
	}
}
</style>
<div class="col-md-8 center">
<div class="card" id="formload">
<div class="card-header">
	<img src="images/logo-color.svg" alt="Logo UVT" style="width:100%;">
<hr>
	<h2>Appel à manifestation d’intérêt pour assurer le tutorat à l’UVT</h2>
	<p>
	De part sa mission d’université transversale œuvrant pour le développement de  l’enseignement à distance à l’échelle du système universitaire tunisien et dans l’objectif de recenser les compétences nationales en ingénierie des formation en ligne, l'UVT lance un appel à manifestation d’intérêt pour l’élargissement de son équipe pédagogique impliquée dans les activités de tutorat des formations diplômantes et éventuellement  certifiantes via la plateforme d’enseignement à distance Moodle.</p>
	</p>
	<p>		Le tutorat concerne l’accompagnement des apprenants à distance et l’élaboration de l’espace de cours</p>
	<p>
		Le présent appel est destiné aux enseignants universitaires rattachés aux universités tunisiennes et aux experts exerçant dans les organismes socio-économiques.
		Les compétences universitaires et professionnelles nationales ayant une expertise en Technologies de l'Information et intéressés par cet appel, sont invitées à consulter les plans de cours des formations displômantes existantes et candidater pour les modules de leurs spécialités. 
	</p>
	
	<p style="color: #800000;text-decoration: underline; ">
Si vous avez déjà déposé une candidature vous pouvez la modifier en cliquant sur le lien suivant : <a href="?activity=demande-modif-ma-candidature"	>Cliquez-ici</a>
	</p>
	<p>Les universitaires et professionnelles nationales intéressés par tutorat sont appelés à déposer leurs candidatures,  en renseignant le formulaire suivant :</p>
	
	
	<b class="text-red">Obligatoire *</b><br>
	
	<div class="progress progress-xs progress-striped active">
		<div class="progress-bar bg-success" id="progressbar" style="width: 0%"></div>
		 
	</div>
	<b id="encours"></b>
</div>

<div class="card-body" id="mainbodyinscript">
<div id="messagewarning"></div>
 <form id="myForm" enctype="multipart/form-data" method="post" action="index.php?activity=saveinscription"   class="form-horizontal">
 
 <div class="form-group row">
	<label for="etab" class="col-sm-3 col-form-label">Formation <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="formation" name="formation" placeholder="Formation" required>
	</select>
	</div>
</div>


 <div class="form-group row">
	<label for="etab" class="col-sm-3 col-form-label">Unité d'enseignement <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="unite" name="unite" placeholder="Unité" required>
	</select>
	</div>
</div>


 

<div class="form-group row">
	<label for="nom" class="col-sm-3 col-form-label">Nom <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="text" class="form-control form-control-lg" id="nom"  name="nom" placeholder="Nom" required>
	</div>
</div>

<div class="form-group row">
	<label for="nom" class="col-sm-3 col-form-label">Prénom <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="text" class="form-control form-control-lg" id="prenom" name="prenom" placeholder="Prénom" required>
	</div>
</div>
<div class="form-group row">
	<label for="cin3" class="col-sm-3 col-form-label"> 03 derniers chiffres de votre CIN (Carte d'identité nationale) <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="number" min="0" max="999" class="form-control form-control-lg" id="cin3" name="cin3"placeholder="3 derniers chiffres CIN" required>
	</div>
</div>
<div class="form-group row">
	<label for="email" class="col-sm-3 col-form-label">Email <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="email" class="form-control form-control-lg" id="email" name="email"placeholder="email" required>
	</div>
</div>

<div class="form-group row">
	<label for="tel" class="col-sm-3 col-form-label">Numéro de téléphone portable <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="text" class="form-control form-control-lg" id="tel" name="tel" placeholder="tel" required>
	</div>
</div>

 <hr>

<div class="form-group row clearfix">
	  <div class="icheck-primary d-inline">
		<input type="radio" id="univprive1" name="univprive"  value="enseignant" checked="checked">
		<label for="univprive1">Enseignant </label>
	  </div>
	  <div class="col-1"></div>
	  <div class="icheck-danger d-inline">
		<input type="radio" id="univprive2" name="univprive" value="professionnel">
		<label for="univprive2">Professionnel </label>
	  </div>
	  
	</div>
	
<hr>	
<div class="form-group row clearfix profesionnel" style="display: none;">
	  <div class="icheck-warning d-inline">
		<input type="radio" id="secteur1" name="secteurjob"  value="Secteur public" checked="checked">
		<label for="secteur1">Secteur public </label>
	  </div>
	  <div class="col-1"></div>
	  <div class="icheck-success  d-inline">
		<input type="radio" id="secteur2" name="secteurjob" value="Secteur privé">
		<label for="secteur2">Secteur privé </label>
	  </div>
	  
	</div>
<div class="form-group row profesionnel"  style="display: none;">
	<label for="nom" class="col-sm-3 col-form-label">Entreprise <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="text" class="form-control form-control-lg" id="entreprise" name="entreprise" placeholder="Entreprise" >
	</div>
</div>

<div class="form-group row profesionnel"  style="display: none;">
	<label for="nom" class="col-sm-3 col-form-label">Poste & Fonction <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="text" class="form-control form-control-lg" id="postefonction" name="postefonction" placeholder="Poste & Fonction">
	</div>
</div>
<div class="form-group row universitaire">
	<label for="univ" class="col-sm-3 col-form-label">Université/DGET <b class="text-red">(Unirevsitaire *)</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="univ" name="univ"  placeholder="univ" required>
	</select>
	</div>
</div>

<div class="form-group row universitaire">
	<label for="etab" class="col-sm-3 col-form-label">Etablissement <b class="text-red">(Unirevsitaire *)</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="etab" name="etab" placeholder="etab" required>
	</select>
	</div>
</div>

<div class="form-group row ">
	<label for="etab" class="col-sm-3 col-form-label">Grade <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<select  class="form-control form-control-lg" id="grade" name="grade" placeholder="grade" required>
	</select>
	</div>
</div>

<div class="form-group row">
	<label for="etab" class="col-sm-3 col-form-label">Spécialité <b class="text-red">*</b></label>
	<div class="col-sm-9">
	 
	<input type="text" class="form-control form-control-lg" id="specialite" name="specialite" placeholder="Spécialité" required>
	</div>
</div>

<div class="form-group row">
	<label for="nom" class="col-sm-3 col-form-label">Dernier diplôme <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="text" class="form-control form-control-lg" id="diplome" name="diplome" placeholder="Dernier diplôme" required>
	</div>
</div>


<div class="form-group row">
	<label for="description" class="col-sm-3 col-form-label">Enumérer les formations effectuées en Tices et EAD </label>
	<div class="col-sm-9">
	<textarea  class="form-control form-control-lg" name="fromationtic" id="fromationtic" placeholder="Enumérer les formations effectuées en Tices et EAD"></textarea>
	</div> 
</div> 


<div class="form-group row">
	<label for="description" class="col-sm-3 col-form-label">Préciser les projets en EAD menés  </label>
	<div class="col-sm-9">
	<textarea  class="form-control form-control-lg" name="projetsEAD" id="projetsEAD" placeholder="Préciser les projets en EAD menés"></textarea>
	</div> 
</div> 


<div class="form-group row">
	<label for="description" class="col-sm-3 col-form-label">Décrire l’expérience avec l’UVT </label>
	<div class="col-sm-9">
	<textarea  class="form-control form-control-lg" name="expuvt" id="expuvt" placeholder="Décrire l’expérience avec l’UVT"></textarea>
	</div> 
</div> 
 
<div class="form-group row">
	<label for="fichierouvre" class="col-sm-3 col-form-label">Déposez votre dossier
  <b class="text-red">*</b> </label>
	<div class="col-sm-9">
	<input type="file" class="form-control form-control-lg" name="fichierouvre" id="fichierouvre" placeholder="Déposez votre œuvre" required>
	</div>
</div>

<p> 
Déposer votre dossier en format ZIP contenant le CV ainsi que toutes les attestations de formation, diplômes et toutes pièces décrivant vos projets et expérience en EAD.
</p>

<div class="visCustomText ">

<p><span style="color: #800000; "><span style="color: #800000;text-decoration: underline; ">NB:</span> La taille maximale du dossier ZIP ne doit pas dépasser <strong>50Mo</strong>, il est conseillé de compresser le fichier avec les formats .zip ou .rar .</span> </p>

<p style="color: #800000;  margin-left: 27px" class="textpmarg"> 
 Le Fichier doit être soumis au format PDF  
</p>

</div>
<br><br>
<div class="form-group row">
	<div class="offset-sm-2 col-sm-9">
	<div class="form-check">
	<input type="checkbox" class="form-check-input" name="signepersonnel" id="signepersonnel" >
	<label class="form-check-label" for="exampleCheck2">Je déclare sur l'honneur ... <b class="text-red">*</b></label>
	</div>
	</div>
</div>
 
<div class="g-recaptcha" data-sitekey="6LdwdIogAAAAAMhaanpwG6Kxlo_gj_sDMcvTkNg3" align="center"></div>
 <hr>
<input class="btn btn-block bg-gradient-primary btn-lg" id="enregistrer" aria-label="Envoyer" value="Envoyer" name="enregistrer" type="submit">
</form>

</div> 
</div>
</div>
