
 <script src='https://www.google.com/recaptcha/api.js'></script>

<SCRIPT type="text/javascript">

$(function() {
	inProgress=false;
	 var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { 
				$("#encours").html(percentComplete);
				$("#progresschifre").html(percentComplete);
				
				$("#progressbar").css({'width': percentComplete+'%'}); 
				if(!inProgress){
				 $("#formload").append("<div id=\"loadzone\" class=\"overlay\" > <i class=\"fas fa-2x fa-sync-alt fa-spin\"i></i><b id=\"progresschifre\"></b></div>");
					inProgress=true;
				}
			},
            success: function() { },
            complete: function(response)
            {


                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                    $("#mainbodyinscript").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Succès')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>");
 
						$("#loadzone").remove(); 
  
                }else if(obj.status=="warning"){
                    $("#mainbodyinscript").html("<div class='alert alert-warning'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Vous n\'êtes pas inscrit')?></h4>"
                        +"<p> "+obj.message
                        +" </p> </div>");
 
						$("#loadzone").remove(); 
  
                }else{

                    $("#progresschifre").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'><?=\Smartedutech\Littlemvc\Langue::getString('Error')?></h4>"
                        +"<p id='merreur'> "+obj.message
                        +" </p> </div>");


                }
                return true;

            },
            error: function(response)
            {
                var obj = JSON.parse(response.responseText);
                $("#progresschifre").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'>Bravo</h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

                return false;
            }

        };

          $("#myForm").ajaxForm(optmyform); 
	
	 	$("#formation").change(function(){
            var opt=$(this).val();
            
			/****************Chargement de la liste des formations**********************/
				$.ajax({
					type:"POST",
					url:"index.php?activity=getunite",
					data:{idformation:opt },
					beforeSend :function(){
						$('#unite').html("<option>Encours... </option>");
					$('#unite').trigger("chosen:updated");
					},
					success:function(response){
						$("#unite").html(response); 
						 
					}
				});
	});
		$.ajax({
			type:"POST",
			url:"index.php?activity=getformation", 
			beforeSend :function(){$('#formation').html("<option>Encours... </option>");$('#formation').trigger("chosen:updated");},
			success:function(response){
				$("#formation").html(response); 
				 
			}
		});
	
	 
});
</SCRIPT>

<style>

@media only screen and (min-width: 768px) {
	.textpmarg{
		line-height : normal;
	}
}

@media only screen and (min-width: 992px) {
	.textpmarg{
		line-height : 0;
	}
}
</style>




<div class="col-md-8 center">
<div class="card" id="formload">
<div class="card-header">
	<img src="images/logo-color.svg" alt="Logo UVT" style="width:100%;">
<hr>
	<h2>Demande de modification de la candidature de tutorat</h2>
	<p>
	Vous recevrez un mail pour la modification de votre candidature, le lien à recevoir ne peut être utilisé qu'une seule fois.
	  </p>
	
	
	
	
</div>

<div class="card-body" id="mainbodyinscript">


<b class="text-red">Obligatoire *</b><br>
	
	<div class="progress progress-xs progress-striped active">
		<div class="progress-bar bg-success" id="progressbar" style="width: 0%"></div>
		 <b id="encours"></b>
	</div>
<hr>

 <form id="myForm" enctype="multipart/form-data" method="post" action="index.php?activity=mailaccortmodif-demande-modif-ma-candidature"   class="form-horizontal">
  
<div class="form-group row">
	<label for="email" class="col-sm-3 col-form-label">Email <b class="text-red">*</b></label>
	<div class="col-sm-9">
	<input type="email" class="form-control form-control-lg" id="email" name="email"placeholder="email" required>
	</div>
</div>
  

<div class="g-recaptcha" data-sitekey="6LdwdIogAAAAAMhaanpwG6Kxlo_gj_sDMcvTkNg3" align="center"></div>
 <hr>
<input class="btn btn-block bg-gradient-primary btn-lg" id="enregistrer" aria-label="Envoyer" value="Envoyer" name="enregistrer" type="submit">
</form>

</div> 
</div>
</div>
